include:
  - project: 'pluralsight/experience/gitlab-helpers'
    file: '/salt-deploy/helper.yml'
  - project: 'pluralsight/experience/gitlab-helpers'
    file: '/helm-deploy/helper.yml'

image: openjdk:8

variables:
  ARTIFACT_NAME: hydra-notifications
  IMAGE_NAME: hydra-notifications
  DOCKER_REGISTRY_URL: harbor.vnerd.com/library
  DOCKER_REGISTRY_IMAGE: ${DOCKER_REGISTRY_URL}/${IMAGE_NAME}
  ARTIFACTORY_REPOSITORY_URL: https://repository.vnerd.com/artifactory
  ARTIFACTORY_REPOSITORY: bounded-context
  ARTIFACTORY_ID: hydra/notifications
  ARTIFACTORY_ARTIFACT_VERSION: ${ARTIFACT_NAME}-${BUILD_VERSION}.tgz
  ARTIFACTORY_PATH: ${ARTIFACTORY_ID}/${ARTIFACTORY_ARTIFACT_VERSION}
  ARTIFACTORY_ARTIFACT_URL: ${ARTIFACTORY_REPOSITORY_URL}/${ARTIFACTORY_REPOSITORY}/${ARTIFACTORY_PATH}
  BUILD_VERSION: 1.0.${CI_PIPELINE_IID}
  BOUNDED_CONTEXT: adapt-dvs


before_script:
  - apt-get update -yqq
  - apt-get install -yqq apt-transport-https apt-utils
  - echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - mkdir -p /root/.gnupg
  - gpg --recv-keys --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/scalasbt-release.gpg --keyserver hkp://keyserver.ubuntu.com:80 2EE0EA64E40A89B84B2DF73499E82A75642AC823
  - chmod 644 /etc/apt/trusted.gpg.d/scalasbt-release.gpg
  - apt-get update -yqq
  - apt-get install -yqq sbt

stages:
  - build
  - package
  - publish
  - deploy-dev

build:
  stage: build
  script:
    - sbt clean compile test
package:
  stage: package
  script:
    - sbt universal:packageBin
    - CURYEAR=$(date +%Y)
    - CURMONTH=$(date +%-m)
    - echo -n "${CURYEAR}.${CURMONTH}.${BUILD_VERSION}" > VERSION
    - pwd
    - ls -lh
    - unzip server/target/universal/*.zip
    - mv hydra-notifications-server-* hydra-notifications-server
    - tar czf ${ARTIFACT_NAME}-${BUILD_VERSION}.tgz --exclude=*.tmp --exclude=*.tgz --exclude=*.tgz.md5 .
    - echo "##teamcity[publishArtifacts '${ARTIFACT_NAME}.tgz']"

  artifacts:
    paths:
      - hydra-notifications-server

publish:
  stage: publish
  image: harbor.vnerd.com/proxy/library/docker:cli
  when: manual
  tags:
    - ps
    - docker
  needs:
    - package
  before_script:
    - echo "$DOCKER_REGISTRY_USERNAME:$DOCKER_REGISTRY_PASSWORD"
    - echo -n "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
  script:
    - pwd
    - ls -lh
    - docker build -t ${IMAGE_NAME} -f Dockerfile .
    - docker tag ${IMAGE_NAME} ${DOCKER_REGISTRY_IMAGE}:${BUILD_VERSION}
    - docker push ${DOCKER_REGISTRY_IMAGE}:${BUILD_VERSION}
  variables:
    DOCKER_HOST: tcp://localhost:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
    DOCKER_TLS_VERIFY: 1

deploy-dev:
    stage: deploy-dev
    needs: ["dvs-data-explorer:build"]
    extends: .helmDeploy
    environment:
      name: staging
    when: manual
    variables:
      HELM_CHART_NAME: dvs-data-explorer
      HELM_DEPLOY_TOKEN: ${HELM_DEPLOY_TOKEN}
      HELM_K8S_CLUSTER_CACERT: ${HELM_K8S_CLUSTER_CACERT}
      HELM_K8S_CLUSTER_URL: https://6C29C0073BB19BEF220B9437E6962AF2.gr7.us-west-2.eks.amazonaws.com
      HELM_TARGET_NAMESPACE: ${BOUNDED_CONTEXT}
      APPLICATION_ROLE: ui
      HELM_VALUES_FILE: helm/eks-dev-values.yaml
    before_script:
      - kubectl config set-cluster app-$CI_ENVIRONMENT_NAME --server=$HELM_K8S_CLUSTER_URL --embed-certs --certificate-authority=$HELM_K8S_CLUSTER_CACERT
      



