include:
  - project: 'pluralsight/experience/gitlab-helpers'
    file: '/slack-notification/helper.yml'
  - project: 'pluralsight/experience/gitlab-helpers'
    file: '/helm-deploy/helper.yml'
image: openjdk:8
variables:
  ARTIFACT_NAME: hydra-notifications
  IMAGE_NAME: hydra-notifications
  DOCKER_REGISTRY_URL: harbor.vnerd.com/library
  DOCKER_REGISTRY_IMAGE: ${DOCKER_REGISTRY_URL}/${IMAGE_NAME}
  ARTIFACTORY_REPOSITORY_URL: https://repository.vnerd.com/artifactory
  ARTIFACTORY_REPOSITORY: bounded-context
  ARTIFACTORY_ID: hydra/notifications
  ARTIFACTORY_ARTIFACT_VERSION: ${ARTIFACT_NAME}-${BUILD_VERSION}.tgz
  ARTIFACTORY_PATH: ${ARTIFACTORY_ID}/${ARTIFACTORY_ARTIFACT_VERSION}
  ARTIFACTORY_ARTIFACT_URL: ${ARTIFACTORY_REPOSITORY_URL}/${ARTIFACTORY_REPOSITORY}/${ARTIFACTORY_PATH}
  BUILD_VERSION: 1.0.${CI_PIPELINE_IID}
  HELM_K8S_CLUSTER_URL: https://6C29C0073BB19BEF220B9437E6962AF2.gr7.us-west-2.eks.amazonaws.com
  K8S_CLUSTER_NAME: app-eks.eplur-staging.us-west-2
  ENV: ${CI_JOB_STAGE} 
  SERVICE_NAME: "hydra-notifications"
  SLACK_ICON_EMOJI: ":gitlab:"
  SLACK_CHANNEL: '#data-platform-alerts'
  SNYK_SLACK_CHANNEL: '#ps-itc-dataops-team'
  SNYK_SLACK_ICON_EMOJI: ":code-ninja:"
  SNYK_ORG_ID: "d8094638-7a37-413f-b1b4-ad840fb9e239"
  SNYK_PROJECT_ID: "cdafcbb5-24d1-4afc-bcda-96055113fc57"
  SNYK_DOCKER_PROJECT_ID: "fea2ede8-3948-4485-9d50-161d262c5a09"
  SLACK_MESSAGE: |
    *[[SERVICE_NAME]]* deployed to *[[ENV]]*.
    Version: *[[BUILD_VERSION]]*
    [[PIPELINE_LINK]]
  SLACK_USERNAME: 'GITLAB'

.startup_script:
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq apt-transport-https apt-utils
    - echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
    - mkdir -p /root/.gnupg
    - gpg --recv-keys --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/scalasbt-release.gpg --keyserver hkp://keyserver.ubuntu.com:80 2EE0EA64E40A89B84B2DF73499E82A75642AC823
    - chmod 644 /etc/apt/trusted.gpg.d/scalasbt-release.gpg
    - apt-get update -yqq
    - apt-get install -yqq sbt curl jq

stages:
  - build
  - package
  - code-analysis
  - publish
  - deploy-dev
  - notify
  - notify_dev
  - deploy-staging
  - notify_staging


build:
  stage: build
  retry: 2
  extends: .startup_script
  script:
    - sbt clean compile test

package:
  stage: package
  retry: 2
  extends: .startup_script
  script:
    - sbt universal:packageBin
    - CURYEAR=$(date +%Y)
    - CURMONTH=$(date +%-m)
    - echo -n "${CURYEAR}.${CURMONTH}.${BUILD_VERSION}" > VERSION
    - unzip server/target/universal/*.zip
    - mv hydra-notifications-server-* hydra-notifications-server
    - tar czf ${ARTIFACT_NAME}-${BUILD_VERSION}.tgz --exclude=/${ARTIFACT_NAME}-${BUILD_VERSION}.tgz --exclude=*.tmp --exclude=*.tgz --exclude=*.tgz.md5 .
    - echo "##teamcity[publishArtifacts '${ARTIFACT_NAME}.tgz']"
  artifacts:
    paths:
      - hydra-notifications-server

snyk-code-analysis:
  stage: code-analysis
  before_script:
    - curl --compressed https://static.snyk.io/cli/latest/snyk-linux -o snyk
    - chmod +x ./snyk
    - mv ./snyk /usr/local/bin/
  allow_failure: true  
  extends: .startup_script    
  script:
    - |
      snyk_ver=$(snyk --version)
      echo "--> Installed SNYK Version:${snyk_ver}"
      if [[ -z "$SNYK_API_TOKEN" && -z "$SNYK_ORG_ID" && -z "$SNYK_PROJECT_ID" ]]; then
        echo "Error While reading required parameters.."
      else
        echo "----- Configuring SNYK -----"
        snyk config set api=${SNYK_API_TOKEN}
        snyk config set org=${SNYK_ORG_ID}
        snyk config set https://app.snyk.io/org/ps-data-services
        echo "--> Iniciating SNYK Code Analysis"
        snyk test --json-file-output="test.json" --all-projects  > snyk-test.json || echo "snyk test completed with errors"
        snyk code test --project-id="${SNYK_PROJECT_ID}" --json --all-projects > snyk-code-analysis.json || echo "snyk test completed with errors"
        echo "--> Code Check Completed"
      fi
  artifacts:
    when: always
    paths:
      - snyk-code-analysis.json
      - snyk-test.json

snyk-code-analysis-notify:
  image: harbor.vnerd.com/library/ps-helm:latest
  stage: code-analysis
  extends: .startup_script
  needs:
    - snyk-code-analysis
  tags:
    - ps
    - docker 
  before_script:
    - echo "Sending SNYK notification to slack"
    - apk update
    - apk add --update --no-cache python3 jq
  script:
    - | 
      MESSAGE=$(python3 ./Snyk/main.py)
      echo $MESSAGE
      #ps-notify slack "$MESSAGE" "$SLACK_CHANNEL"  --slack-username $SLACK_USERNAME --slack-icon-emoji $SLACK_ICON_EMOJI
  variables:
    NODE_ENV: $ENV  
    ENV: $ENV
    SERVICE_NAME: "dev-hydra-notifications"
    SLACK_CHANNEL: "#dataops-test"
    SLACK_ICON_EMOJI: ":alert:"

publish:
  stage: publish
  image: harbor.vnerd.com/proxy/library/docker:cli
  extends: .startup_script
  tags:
    - ps
    - docker
  needs:
    - package
    - snyk-code-analysis
    - snyk-code-analysis-notify
  before_script:
    - echo "$DOCKER_REGISTRY_USERNAME:$DOCKER_REGISTRY_PASSWORD"
    - echo -n "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
    - apk add libstdc++ curl 
    - curl --compressed https://static.snyk.io/cli/latest/snyk-alpine -o snyk
    - chmod +x ./snyk
    - mv ./snyk /usr/local/bin
    - | 
      snyk_ver=$(snyk --version)
      echo "--> Installed SNYK Version:${snyk_ver}"
      if [[ -z "$SNYK_API_TOKEN" && -z "$SNYK_ORG_ID" && -z "$SNYK_PROJECT_ID" ]]; then
        echo "Error While reading required parameters.."
      else
        echo "----- Configuring SNYK Api Token and Org -----"
        snyk config set api=${SNYK_API_TOKEN}
        snyk config set org=${SNYK_ORG_ID}
      fi
  script:
    - docker build -t ${IMAGE_NAME} -f Dockerfile .
    - docker tag ${IMAGE_NAME} ${DOCKER_REGISTRY_IMAGE}:${BUILD_VERSION}
    - docker push ${DOCKER_REGISTRY_IMAGE}:${BUILD_VERSION}
    - echo "--> Performing Static Code Analysis"
    - snyk container test ${DOCKER_REGISTRY_IMAGE}:${BUILD_VERSION} --file=${CI_PROJECT_DIR}/Dockerfile --json --report --project-id="${SNYK_DOCKER_PROJECT_ID}" > snyk-container-vul.json
  variables:
    DOCKER_HOST: tcp://localhost:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
    DOCKER_TLS_VERIFY: 1
  artifacts:
    when: always
    paths:
      - snyk-container-vul.json

slack:notify-vulnerability:
  stage: publish
  image: harbor.vnerd.com/library/ps-helm:latest
  extends: .startup_script
  tags:
    - ps
    - docker 
  script:
    - | 
      TOTAL_VUL=$( cat snyk-container-vul.json | jq ".uniqueCount")
      MESSAGE="Found $TOTAL_VUL vulnerability in *[[SERVICE_NAME]]* 
      COMMIT_ID: ${CI_COMMIT_SHORT_SHA}
      [[PIPELINE_LINK]]"
      ps-notify slack "$MESSAGE" "$SLACK_CHANNEL"  --slack-username $SLACK_USERNAME --slack-icon-emoji $SLACK_ICON_EMOJI
  when: always
  needs: ['publish','snyk-code-analysis']
  before_script:
    - echo "Sending notification to slack"
    - apk update
    - apk add jq
  variables:
    ENV: $ENV
    SERVICE_NAME: "dev-hydra-notifications"
    SLACK_CHANNEL: "#dataops-test"
    SLACK_ICON_EMOJI: ":alert:"

.notify-all:
  image: harbor.vnerd.com/library/ps-helm:latest
  extends: .startup_script
  tags:
    - ps
    - docker 
  script:
    - ps-notify slack "$SLACK_MESSAGE" "$SLACK_CHANNEL"  --slack-username $SLACK_USERNAME --slack-icon-emoji $SLACK_ICON_EMOJI
  variables:
    NODE_ENV: $ENV

deploy-dev:
    stage: deploy-dev
    extends: .helmDeploy
    environment:
      name: dev
    variables:
      HELM_CHART_NAME: ps-service
      HELM_DEPLOY_TOKEN: ${HELM_DEPLOY_TOKEN}
      K8S_CLUSTER_NAME: app-eks.eplur-staging.us-west-2
      HELM_K8S_CLUSTER_URL: https://6C29C0073BB19BEF220B9437E6962AF2.gr7.us-west-2.eks.amazonaws.com
      BOUNDED_CONTEXT: adapt-dvs-dev
      HELM_TARGET_NAMESPACE: ${BOUNDED_CONTEXT}
      APPLICATION_ROLE: dev-hydra-notifications
      HELM_VALUES_FILE: helm/eks-dev-values.yml
      HELM_SET_VALUES: "NODE_ENV=production, INGEST_URL=https://dev-hydra.eplur-staging.vnerd.com, PUBLIC_URL=https://dvs-dev.eplur-staging.vnerd.com/dvs-data-explorer, REACT_APP_INGEST_URL=https://dev-hydra.eplur-staging.vnerd.com, REACT_APP_STREAMS_URL=https://hydra-streams-dev.eplur-staging.vnerd.com, STREAMS_URL=https://hydra-streams-dev.eplur-staging.vnerd.com"
    before_script:
      - export BUILD_VERSION="$(date +%Y).$(date +%m).$(date +%d).${CI_COMMIT_SHORT_SHA}"
      - kubectl config set-cluster app-${CI_ENVIRONMENT_NAME%/*} --server=${HELM_K8S_CLUSTER_URL} --embed-certs --certificate-authority="$HELM_K8S_CLUSTER_CACERT"
      - kubectl config set-credentials deploy --token=`echo ${HELM_DEPLOY_TOKEN} | base64 -d`
      - kubectl config set-context deploy --cluster=app-${CI_ENVIRONMENT_NAME%/*} --namespace=${HELM_TARGET_NAMESPACE} --user=deploy
      - kubectl config use-context deploy

slack:dev:
  stage: notify_dev
  extends: .notify-all
  when: on_success
  needs: ['deploy-dev']
  before_script:
    - echo "Sending notification to slack"
  variables:
    ENV: "DEV Cluster"
    SERVICE_NAME: "dev-hydra-notifications"

deploy-staging:
    stage: deploy-staging
    extends: .helmDeploy
    when: manual
    environment:
      name: staging
    variables:
      HELM_CHART_NAME: ps-service
      HELM_DEPLOY_TOKEN: ${HELM_DEPLOY_TOKEN}
      K8S_CLUSTER_NAME: app-eks.eplur-staging.us-west-2
      HELM_K8S_CLUSTER_URL: https://6C29C0073BB19BEF220B9437E6962AF2.gr7.us-west-2.eks.amazonaws.com
      BOUNDED_CONTEXT: adapt-dvs
      HELM_TARGET_NAMESPACE: ${BOUNDED_CONTEXT}
      APPLICATION_ROLE: is-hydra-notifications
      HELM_VALUES_FILE: helm/eks-staging-values.yml
      HELM_SET_VALUES: "NODE_ENV=production, INGEST_URL=https://hydra-publish.eplur-staging.vnerd.com, PUBLIC_URL=https://dvs.eplur-staging.vnerd.com/dvs-data-explorer, REACT_APP_INGEST_URL=https://hydra-publish.eplur-staging.vnerd.com, REACT_APP_STREAMS_URL=https://hydra-streams.eplur-staging.vnerd.com, STREAMS_URL=https://hydra-streams.eplur-staging.vnerd.com"
    before_script:
      - export BUILD_VERSION="$(date +%Y).$(date +%m).$(date +%d).${CI_COMMIT_SHORT_SHA}"
      - kubectl config set-cluster app-${CI_ENVIRONMENT_NAME%/*} --server=${HELM_K8S_CLUSTER_URL} --embed-certs --certificate-authority="$HELM_K8S_CLUSTER_CACERT"
      - kubectl config set-credentials deploy --token=`echo ${HELM_DEPLOY_TOKEN} | base64 -d`
      - kubectl config set-context deploy --cluster=app-${CI_ENVIRONMENT_NAME%/*} --namespace=${HELM_TARGET_NAMESPACE} --user=deploy
      - kubectl config use-context deploy

slack:staging:
  stage: notify_staging
  extends: .notify-all
  when: on_success
  needs: ['deploy-staging']
  before_script:
    - echo "Sending notification to slack"
  variables:
    ENV: "STAGING Cluster"
    SERVICE_NAME: "is-hydra-notifications"