image:
  repository: harbor.vnerd.com/library/dvs-data-explorer
  pullPolicy: Always
  tag: latest

deployment:
  apiVersion: "apps/v1"
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate

replicas: 2

service:
  type: ClusterIP
  port: 80
  annotations: {}
  labels: {}

ingress:
  enabled: true
  ingressClassName: internal
  annotations: {}
  labels: {}
  hosts:
    - hydra-notifications.eplur-production.vnerd.com
    - hydra-notifications.vnerd.com
    - hydra-notifications-production.vnerd.com
  tls:
    - hosts:
        - hydra-notifications-production.vnerd.com
  path: /
  pathType: Prefix

resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 2
    memory: 1Gi

tolerations: []

nodeSelector: {}

config:
  LOG_DIR: /var/log/hydra-notifications
  LOG_LEVEL: ERROR
  PORT_NUMBER: 8080
  SLACK_TOKEN: 
  OPSGENIE_TOKEN: 
  STREAMS_URL: https://hydra-streams-dev.eplur-staging.vnerd.com
